services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helidon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-container
    command: [
      "liquibase",
      "--url=jdbc:postgresql://postgres-container:5432/helidon?user=user&password=password",
      "--changelog-file=/changelog/changelog.yaml",
      "update",
    ]
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/db:/liquibase/db
    depends_on:
      - postgres

  ai-runner:
    provider:
      type: model
      options:
        model : ai/deepseek-r1-distill-llama:8B-Q4_K_M

#  metric-service:
#    build:
#      context: .
#    environment:
#      db.connection.url: jdbc:postgresql://postgres-container:5432/helidon
#      db.connection.username: user
#      db.connection.password: password
#      mail.host:
#      mail.port:
#      mail.username:
#      mail.password:
#      mail.recipient:
#      AI_RUNNER_MODEL: ai/deepseek-r1-distill-llama:8B-Q4_K_M
#    ports:
#      - "8080:8080"
#    depends_on:
#      liquibase:
#        condition: service_completed_successfully
#      ai-runner:
#        condition: service_started

volumes:
  postgres_data:
    driver: local