services:

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helidon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-container
    command: [
      "liquibase",
      "--url=jdbc:postgresql://postgres-container:5432/helidon?user=user&password=password",
      "--changelog-file=/changelog/changelog.yaml",
      "update",
    ]
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/db:/liquibase/db
    depends_on:
      - postgres

  metric-service:
    build:
      context: .
    environment:
      db.connection.url: jdbc:postgresql://postgres-container:5432/helidon
      db.connection.username: user
      db.connection.password: password
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully

volumes:
  postgres_data:
    driver: local