openapi: 3.1.0
info:
  title: Metrics service
  description: A simple application that serves metricdata
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local
paths:
  /metrics:
    post:
      summary: Save new metrics data
      description: Endpoint to save metrics data
      parameters:
        - $ref: '#/components/parameters/repository-id'
      requestBody:
        $ref: '#/components/requestBodies/metrics-request-body'

      responses:
        200:
          description: Data was persisted successfully
        400:
          description: Bad request
        500:
          description: Internal server error

    get:
      summary: Retrieve metrics filtered by repository, date range, and optionally metric name
      description: Retrieve metrics for a given repository within a specified date range.
        Optionally, include a metric name as a query param to filter results to a specific metric.
      parameters:
        - $ref: '#/components/parameters/repository-id'
        - $ref: '#/components/parameters/metric-name'
        - $ref: '#/components/parameters/date-from'
        - $ref: '#/components/parameters/date-to'
      responses:
        200:
          description: Data was fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metrics'

        500:
          description: Internal server error
        404:
          description: Not found

  /metrics/recent:
    get:
      summary: Retrieve recent metrics from the past 30 days
      description: Returns a snapshot of repository metrics collected over the past 30 days, sourced from a materialized view for performance.
      parameters:
        - $ref: '#/components/parameters/repository-id'
      responses:
        200:
          description: Data was fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metrics'

        500:
          description: Internal server error
        404:
          description: Not found

  /metrics/analyze:
    post:
      summary: Analyze metrics data using AI
      description: | 
       Submit metrics data to the AI service for analysis and insights generation.
       Note: The results may not be reliable and should be interpreted with caution.

      responses:
        200:
          description: All ok
          content:
            application:json:
              schema:
                type: string

        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Internal server error



components:
  parameters:
    repository-id:
      name: Repository-Id
      in: header
      description: ID of the repository
      required: true
      schema:
        type: string
        example: repo-1
    metric-name:
      name: name
      in: query
      description: |
        The query parameter containing the wanted metric over a timespan period.
      required: false
      schema:
        type: string
        description: The query parameter containing the wanted metric over a timespan period.
        example: "http_req_duration"
    date-from:
      name: from
      in: query
      description: |
        The query parameter containing the start date of the search.
        Note: The colon (':') in the date-time value needs to be URL encoded as '%3A'.
      required: true
      schema:
        type: string
        description: The start date to look from (e.g., "2017-01-01T00:00:00Z").
        example: "2017-01-01T00:00:00Z"
        format: date-time
    date-to:
      name: to
      in: query
      description: |
        The query parameter containing the end date of the search.
        Note: The colon (':') in the date-time value needs to be URL encoded as '%3A'.
      required: true
      schema:
        type: string
        description: The end date to look until (e.g., "2017-01-02T00:00:00Z").
        example: "2027-01-02T00:00:00Z"
        format: date-time

  requestBodies:
    metrics-request-body:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Metric-Request-Object'

    metric-report-recent-response:
      content:
        application/json:
          schema:
            $ref: #/components/schemas/Metric-Recent-Response-Object'

  schemas:
    Metric-Request-Object:
      description: Object that holds specific metrics data
      type: object
      required:
        - metrics
      properties:
        metrics:
          type: object
          additionalProperties:
            type: object
            description: Specific metric object
            properties:
              type:
                type: string
                description: Type of the metric (e.g., "rate", "counter", "trend", "gauge")
              values:
                type: object
                additionalProperties:
                  type: number
                  description: Metric values (e.g., "rate", "avg", "min", etc.)
      example:
        options:
          summaryTrendStats: [ "avg", "min", "med", "max", "p(90)", "p(95)" ]
          summaryTimeUnit: ""
          noColor: false
        state:
          isStdOutTTY: true
          isStdErrTTY: true
          testRunDurationMs: 10013.6525
        metrics:
          http_req_failed:
            type: "rate"
            values:
              rate: 0
              passes: 0
              fails: 100
          data_received:
            type: "counter"
            values:
              count: 10600
              rate: 1058.5548080483122

    Metrics:
      description: Object that holds multiple metrics data
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the metric data
        data:
          type: string
          description: JSON-encoded string containing the metric data
        timestamp:
          type: string
          format: date-time
          description: Timestamp for when the data was collected
          example: "2025-04-25T12:34:56Z"
        metricList:
          type: array
          items:
            $ref: '#/components/schemas/Metric'
          description: A list of additional metrics

    Metric:
      description: Object that hold specific metric information
      properties:
        type:
          type: string
          description: Type of the metric (e.g., "rate", "counter", "trend", "gauge")
        values:
          type: object
          additionalProperties:
            type: number
            description: Metric values (e.g., "rate", "avg", "min", etc.)
      example:
        http_req_failed:
          type: "rate"
          values:
            rate: 0
            passes: 0
            fails: 100
