server:
  port: 8080
  host: "localhost"

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/helidon"
    username: "user"
    password: "password"
  statements:
    insertMetrics: "INSERT INTO metrics VALUES (?, ?::JSON, ?)"
    insertSingleMetric: "INSERT INTO metric VALUES (?, ?, ?, ?)"


